cmd_arch/mips/brcmstb/standby.o := mipsel-unknown-linux-gnu-gcc -Wp,-MD,arch/mips/brcmstb/.standby.o.d -nostdinc -isystem /home/atef/buildsystem-ddt/cross/mips-gcc-10.5.0-kernel-3.4-4.0/lib/gcc/mipsel-unknown-linux-gnu/10.5.0/include -I/home/atef/buildsystem-ddt/build_tmp/linux-3.4.113/arch/mips/include -Iarch/mips/include/generated -Iinclude  -include /home/atef/buildsystem-ddt/build_tmp/linux-3.4.113/include/linux/kconfig.h -D__KERNEL__ -D"VMLINUX_LOAD_ADDRESS=0x80001000" -D"DATAOFFSET=0" -D__ASSEMBLY__  -mno-check-zero-division -mabi=32 -G 0 -mno-abicalls -fno-pic -pipe -msoft-float -DGAS_HAS_SET_HARDFLOAT -Wa,-msoft-float -ffreestanding  -march=mips32 -Wa,-mips32 -Wa,--trap -I/home/atef/buildsystem-ddt/build_tmp/linux-3.4.113/arch/mips/include/asm/mach-brcmstb -Wno-error=array-bounds -I/home/atef/buildsystem-ddt/build_tmp/linux-3.4.113/arch/mips/include/asm/mach-generic        -c -o arch/mips/brcmstb/standby.o arch/mips/brcmstb/standby.S

source_arch/mips/brcmstb/standby.o := arch/mips/brcmstb/standby.S

deps_arch/mips/brcmstb/standby.o := \
    $(wildcard include/config/cpu/bmips5000.h) \
    $(wildcard include/config/brcm/has/analog/ddr/phy.h) \
    $(wildcard include/config/brcm/pwr/handshake.h) \
    $(wildcard include/config/bcm7346.h) \
    $(wildcard include/config/bcm7425.h) \
    $(wildcard include/config/brcm/pwr/handshake/v0.h) \
    $(wildcard include/config/brcm/pwr/handshake/v1.h) \
    $(wildcard include/config/brcm/has/digital/ddr/phy.h) \
  /home/atef/buildsystem-ddt/build_tmp/linux-3.4.113/arch/mips/include/asm/asm.h \
    $(wildcard include/config/printk.h) \
    $(wildcard include/config/cpu/has/prefetch.h) \
    $(wildcard include/config/sgi/ip28.h) \
  /home/atef/buildsystem-ddt/build_tmp/linux-3.4.113/arch/mips/include/asm/sgidefs.h \
  /home/atef/buildsystem-ddt/build_tmp/linux-3.4.113/arch/mips/include/asm/regdef.h \
  /home/atef/buildsystem-ddt/build_tmp/linux-3.4.113/arch/mips/include/asm/mipsregs.h \
    $(wildcard include/config/cpu/vr41xx.h) \
    $(wildcard include/config/page/size/4kb.h) \
    $(wildcard include/config/page/size/8kb.h) \
    $(wildcard include/config/page/size/16kb.h) \
    $(wildcard include/config/page/size/32kb.h) \
    $(wildcard include/config/page/size/64kb.h) \
    $(wildcard include/config/hugetlb/page.h) \
    $(wildcard include/config/mips/mt/smtc.h) \
  include/linux/linkage.h \
  include/linux/compiler.h \
    $(wildcard include/config/sparse/rcu/pointer.h) \
    $(wildcard include/config/trace/branch/profiling.h) \
    $(wildcard include/config/profile/all/branches.h) \
    $(wildcard include/config/enable/must/check.h) \
    $(wildcard include/config/enable/warn/deprecated.h) \
  /home/atef/buildsystem-ddt/build_tmp/linux-3.4.113/arch/mips/include/asm/linkage.h \
  /home/atef/buildsystem-ddt/build_tmp/linux-3.4.113/arch/mips/include/asm/hazards.h \
    $(wildcard include/config/cpu/mipsr2.h) \
    $(wildcard include/config/cpu/cavium/octeon.h) \
    $(wildcard include/config/cpu/mipsr1.h) \
    $(wildcard include/config/mips/alchemy.h) \
    $(wildcard include/config/cpu/bmips.h) \
    $(wildcard include/config/cpu/loongson2.h) \
    $(wildcard include/config/cpu/r10000.h) \
    $(wildcard include/config/cpu/r5500.h) \
    $(wildcard include/config/cpu/rm9000.h) \
    $(wildcard include/config/cpu/sb1.h) \
  /home/atef/buildsystem-ddt/build_tmp/linux-3.4.113/arch/mips/include/asm/war.h \
    $(wildcard include/config/cpu/r4000/workarounds.h) \
    $(wildcard include/config/cpu/r4400/workarounds.h) \
    $(wildcard include/config/cpu/daddi/workarounds.h) \
  /home/atef/buildsystem-ddt/build_tmp/linux-3.4.113/arch/mips/include/asm/mach-brcmstb/war.h \
  /home/atef/buildsystem-ddt/build_tmp/linux-3.4.113/arch/mips/include/asm/cacheops.h \
  /home/atef/buildsystem-ddt/build_tmp/linux-3.4.113/arch/mips/include/asm/addrspace.h \
    $(wildcard include/config/64bit.h) \
    $(wildcard include/config/brcm/upper/768mb.h) \
    $(wildcard include/config/cpu/r8000.h) \
  /home/atef/buildsystem-ddt/build_tmp/linux-3.4.113/arch/mips/include/asm/mach-brcmstb/spaces.h \
    $(wildcard include/config/brcm/upper/memory.h) \
    $(wildcard include/config/brcm/has/2gb/memc0.h) \
  include/linux/const.h \
  /home/atef/buildsystem-ddt/build_tmp/linux-3.4.113/arch/mips/include/asm/mach-generic/spaces.h \
    $(wildcard include/config/32bit.h) \
    $(wildcard include/config/dma/noncoherent.h) \
  include/linux/brcmstb/brcmstb.h \
    $(wildcard include/config/mips.h) \
    $(wildcard include/config/bcm7228a0.h) \
    $(wildcard include/config/bcm7231b0.h) \
    $(wildcard include/config/bcm7344b0.h) \
    $(wildcard include/config/bcm7346b0.h) \
    $(wildcard include/config/bcm7358a0.h) \
    $(wildcard include/config/bcm7360a0.h) \
    $(wildcard include/config/bcm7362a0.h) \
    $(wildcard include/config/bcm7425b0.h) \
    $(wildcard include/config/bcm7429b0.h) \
    $(wildcard include/config/bcm7435b0.h) \
    $(wildcard include/config/bcm7543a0.h) \
    $(wildcard include/config/bcm7552b0.h) \
    $(wildcard include/config/bcm7563a0.h) \
    $(wildcard include/config/bcm7584a0.h) \
    $(wildcard include/config/brcm/slow/tvm/clock.h) \
    $(wildcard include/config/brcm/has/wktmr.h) \
  /home/atef/buildsystem-ddt/build_tmp/linux-3.4.113/arch/mips/include/asm/bmips.h \
    $(wildcard include/config/1.h) \
  include/linux/brcmstb/7435b0/bchp_aon_ctrl.h \
  include/linux/brcmstb/7435b0/bchp_aon_pin_ctrl.h \
  include/linux/brcmstb/7435b0/bchp_aon_pm_l2.h \
  include/linux/brcmstb/7435b0/bchp_bspi.h \
  include/linux/brcmstb/7435b0/bchp_bspi_raf.h \
  include/linux/brcmstb/7435b0/bchp_clkgen.h \
  include/linux/brcmstb/7435b0/bchp_common.h \
    $(wildcard include/config/reg/start.h) \
    $(wildcard include/config/reg/end.h) \
  include/linux/brcmstb/7435b0/bchp_ddr40_phy_control_regs_0.h \
    $(wildcard include/config/reserved0/mask.h) \
    $(wildcard include/config/reserved0/shift.h) \
    $(wildcard include/config/lp40/pll/post/reset/mask.h) \
    $(wildcard include/config/lp40/pll/post/reset/shift.h) \
    $(wildcard include/config/lp40/pll/post/reset/default.h) \
    $(wildcard include/config/reset/post/div/mask.h) \
    $(wildcard include/config/reset/post/div/shift.h) \
    $(wildcard include/config/reset/post/div/default.h) \
    $(wildcard include/config/ldo/ctrl/mask.h) \
    $(wildcard include/config/ldo/ctrl/shift.h) \
    $(wildcard include/config/ldo/ctrl/default.h) \
    $(wildcard include/config/reserved1/mask.h) \
    $(wildcard include/config/reserved1/shift.h) \
    $(wildcard include/config/reset/mask.h) \
    $(wildcard include/config/reset/shift.h) \
    $(wildcard include/config/reset/default.h) \
    $(wildcard include/config/pwrdn/mask.h) \
    $(wildcard include/config/pwrdn/shift.h) \
    $(wildcard include/config/pwrdn/default.h) \
  include/linux/brcmstb/7435b0/bchp_ddr40_phy_control_regs_1.h \
  include/linux/brcmstb/7435b0/bchp_ddr40_phy_word_lane_0_0.h \
  include/linux/brcmstb/7435b0/bchp_ddr40_phy_word_lane_0_1.h \
  include/linux/brcmstb/7435b0/bchp_ddr40_phy_word_lane_1_0.h \
  include/linux/brcmstb/7435b0/bchp_ddr40_phy_word_lane_1_1.h \
  include/linux/brcmstb/7435b0/bchp_ebi.h \
    $(wildcard include/config/0.h) \
    $(wildcard include/config/2.h) \
    $(wildcard include/config/3.h) \
    $(wildcard include/config/4.h) \
    $(wildcard include/config/5.h) \
    $(wildcard include/config/0/mem/io/mask.h) \
    $(wildcard include/config/0/mem/io/shift.h) \
    $(wildcard include/config/0/mem/io/default.h) \
    $(wildcard include/config/0/ta/wait/mask.h) \
    $(wildcard include/config/0/ta/wait/shift.h) \
    $(wildcard include/config/0/ta/wait/default.h) \
    $(wildcard include/config/0/wp/mask.h) \
    $(wildcard include/config/0/wp/shift.h) \
    $(wildcard include/config/0/wp/default.h) \
    $(wildcard include/config/0/wait/count/mask.h) \
    $(wildcard include/config/0/wait/count/shift.h) \
    $(wildcard include/config/0/wait/count/default.h) \
    $(wildcard include/config/0/t/hold/mask.h) \
    $(wildcard include/config/0/t/hold/shift.h) \
    $(wildcard include/config/0/t/hold/default.h) \
    $(wildcard include/config/0/t/setup/mask.h) \
    $(wildcard include/config/0/t/setup/shift.h) \
    $(wildcard include/config/0/t/setup/default.h) \
    $(wildcard include/config/0/cs/hold/mask.h) \
    $(wildcard include/config/0/cs/hold/shift.h) \
    $(wildcard include/config/0/cs/hold/default.h) \
    $(wildcard include/config/0/split/cs/mask.h) \
    $(wildcard include/config/0/split/cs/shift.h) \
    $(wildcard include/config/0/split/cs/default.h) \
    $(wildcard include/config/0/mask/en/mask.h) \
    $(wildcard include/config/0/mask/en/shift.h) \
    $(wildcard include/config/0/mask/en/default.h) \
    $(wildcard include/config/0/ne/sample/mask.h) \
    $(wildcard include/config/0/ne/sample/shift.h) \
    $(wildcard include/config/0/ne/sample/default.h) \
    $(wildcard include/config/0/m68k/mask.h) \
    $(wildcard include/config/0/m68k/shift.h) \
    $(wildcard include/config/0/m68k/default.h) \
    $(wildcard include/config/0/le/mask.h) \
    $(wildcard include/config/0/le/shift.h) \
    $(wildcard include/config/0/fast/read/mask.h) \
    $(wildcard include/config/0/fast/read/shift.h) \
    $(wildcard include/config/0/fast/read/default.h) \
    $(wildcard include/config/0/fast/read/normal.h) \
    $(wildcard include/config/0/fast/read/fast/read/enable.h) \
    $(wildcard include/config/0/size/sel/mask.h) \
    $(wildcard include/config/0/size/sel/shift.h) \
    $(wildcard include/config/0/size/sel/default.h) \
    $(wildcard include/config/0/sync/mask.h) \
    $(wildcard include/config/0/sync/shift.h) \
    $(wildcard include/config/0/sync/default.h) \
    $(wildcard include/config/0/polarity/mask.h) \
    $(wildcard include/config/0/polarity/shift.h) \
    $(wildcard include/config/0/polarity/default.h) \
    $(wildcard include/config/0/we/ctl/mask.h) \
    $(wildcard include/config/0/we/ctl/shift.h) \
    $(wildcard include/config/0/we/ctl/default.h) \
    $(wildcard include/config/0/dest/size/mask.h) \
    $(wildcard include/config/0/dest/size/shift.h) \
    $(wildcard include/config/0/ms/inh/mask.h) \
    $(wildcard include/config/0/ms/inh/shift.h) \
    $(wildcard include/config/0/ms/inh/default.h) \
    $(wildcard include/config/0/ls/inh/mask.h) \
    $(wildcard include/config/0/ls/inh/shift.h) \
    $(wildcard include/config/0/ls/inh/default.h) \
    $(wildcard include/config/0/bcachen/mask.h) \
    $(wildcard include/config/0/bcachen/shift.h) \
    $(wildcard include/config/0/bcachen/default.h) \
    $(wildcard include/config/0/enable/mask.h) \
    $(wildcard include/config/0/enable/shift.h) \
    $(wildcard include/config/0/enable/default.h) \
    $(wildcard include/config/1/mem/io/mask.h) \
    $(wildcard include/config/1/mem/io/shift.h) \
    $(wildcard include/config/1/mem/io/default.h) \
    $(wildcard include/config/1/ta/wait/mask.h) \
    $(wildcard include/config/1/ta/wait/shift.h) \
    $(wildcard include/config/1/ta/wait/default.h) \
    $(wildcard include/config/1/wp/mask.h) \
    $(wildcard include/config/1/wp/shift.h) \
    $(wildcard include/config/1/wp/default.h) \
    $(wildcard include/config/1/wait/count/mask.h) \
    $(wildcard include/config/1/wait/count/shift.h) \
    $(wildcard include/config/1/wait/count/default.h) \
    $(wildcard include/config/1/t/hold/mask.h) \
    $(wildcard include/config/1/t/hold/shift.h) \
    $(wildcard include/config/1/t/hold/default.h) \
    $(wildcard include/config/1/t/setup/mask.h) \
    $(wildcard include/config/1/t/setup/shift.h) \
    $(wildcard include/config/1/t/setup/default.h) \
    $(wildcard include/config/1/cs/hold/mask.h) \
    $(wildcard include/config/1/cs/hold/shift.h) \
    $(wildcard include/config/1/cs/hold/default.h) \
    $(wildcard include/config/1/split/cs/mask.h) \
    $(wildcard include/config/1/split/cs/shift.h) \
    $(wildcard include/config/1/split/cs/default.h) \
    $(wildcard include/config/1/mask/en/mask.h) \
    $(wildcard include/config/1/mask/en/shift.h) \
    $(wildcard include/config/1/mask/en/default.h) \
    $(wildcard include/config/1/ne/sample/mask.h) \
    $(wildcard include/config/1/ne/sample/shift.h) \
    $(wildcard include/config/1/ne/sample/default.h) \
    $(wildcard include/config/1/m68k/mask.h) \
    $(wildcard include/config/1/m68k/shift.h) \
    $(wildcard include/config/1/m68k/default.h) \
    $(wildcard include/config/1/le/mask.h) \
    $(wildcard include/config/1/le/shift.h) \
    $(wildcard include/config/1/le/default.h) \
    $(wildcard include/config/1/fast/read/mask.h) \
    $(wildcard include/config/1/fast/read/shift.h) \
    $(wildcard include/config/1/fast/read/default.h) \
    $(wildcard include/config/1/fast/read/normal.h) \
    $(wildcard include/config/1/fast/read/fast/read/enable.h) \
    $(wildcard include/config/1/size/sel/mask.h) \
    $(wildcard include/config/1/size/sel/shift.h) \
    $(wildcard include/config/1/size/sel/default.h) \
    $(wildcard include/config/1/sync/mask.h) \
    $(wildcard include/config/1/sync/shift.h) \
    $(wildcard include/config/1/sync/default.h) \
    $(wildcard include/config/1/polarity/mask.h) \
    $(wildcard include/config/1/polarity/shift.h) \
    $(wildcard include/config/1/polarity/default.h) \
    $(wildcard include/config/1/we/ctl/mask.h) \
    $(wildcard include/config/1/we/ctl/shift.h) \
    $(wildcard include/config/1/we/ctl/default.h) \
    $(wildcard include/config/1/dest/size/mask.h) \
    $(wildcard include/config/1/dest/size/shift.h) \
    $(wildcard include/config/1/dest/size/default.h) \
    $(wildcard include/config/1/ms/inh/mask.h) \
    $(wildcard include/config/1/ms/inh/shift.h) \
    $(wildcard include/config/1/ms/inh/default.h) \
    $(wildcard include/config/1/ls/inh/mask.h) \
    $(wildcard include/config/1/ls/inh/shift.h) \
    $(wildcard include/config/1/ls/inh/default.h) \
    $(wildcard include/config/1/bcachen/mask.h) \
    $(wildcard include/config/1/bcachen/shift.h) \
    $(wildcard include/config/1/bcachen/default.h) \
    $(wildcard include/config/1/enable/mask.h) \
    $(wildcard include/config/1/enable/shift.h) \
    $(wildcard include/config/1/enable/default.h) \
    $(wildcard include/config/2/mem/io/mask.h) \
    $(wildcard include/config/2/mem/io/shift.h) \
    $(wildcard include/config/2/mem/io/default.h) \
    $(wildcard include/config/2/ta/wait/mask.h) \
    $(wildcard include/config/2/ta/wait/shift.h) \
    $(wildcard include/config/2/ta/wait/default.h) \
    $(wildcard include/config/2/wp/mask.h) \
    $(wildcard include/config/2/wp/shift.h) \
    $(wildcard include/config/2/wp/default.h) \
    $(wildcard include/config/2/wait/count/mask.h) \
    $(wildcard include/config/2/wait/count/shift.h) \
    $(wildcard include/config/2/wait/count/default.h) \
    $(wildcard include/config/2/t/hold/mask.h) \
    $(wildcard include/config/2/t/hold/shift.h) \
    $(wildcard include/config/2/t/hold/default.h) \
    $(wildcard include/config/2/t/setup/mask.h) \
    $(wildcard include/config/2/t/setup/shift.h) \
    $(wildcard include/config/2/t/setup/default.h) \
    $(wildcard include/config/2/cs/hold/mask.h) \
    $(wildcard include/config/2/cs/hold/shift.h) \
    $(wildcard include/config/2/cs/hold/default.h) \
    $(wildcard include/config/2/split/cs/mask.h) \
    $(wildcard include/config/2/split/cs/shift.h) \
    $(wildcard include/config/2/split/cs/default.h) \
    $(wildcard include/config/2/mask/en/mask.h) \
    $(wildcard include/config/2/mask/en/shift.h) \
    $(wildcard include/config/2/mask/en/default.h) \
    $(wildcard include/config/2/ne/sample/mask.h) \
    $(wildcard include/config/2/ne/sample/shift.h) \
    $(wildcard include/config/2/ne/sample/default.h) \
    $(wildcard include/config/2/m68k/mask.h) \
    $(wildcard include/config/2/m68k/shift.h) \
    $(wildcard include/config/2/m68k/default.h) \
    $(wildcard include/config/2/le/mask.h) \
    $(wildcard include/config/2/le/shift.h) \
    $(wildcard include/config/2/le/default.h) \
    $(wildcard include/config/2/fast/read/mask.h) \
    $(wildcard include/config/2/fast/read/shift.h) \
    $(wildcard include/config/2/fast/read/default.h) \
    $(wildcard include/config/2/fast/read/normal.h) \
    $(wildcard include/config/2/fast/read/fast/read/enable.h) \
    $(wildcard include/config/2/size/sel/mask.h) \
    $(wildcard include/config/2/size/sel/shift.h) \
    $(wildcard include/config/2/size/sel/default.h) \
    $(wildcard include/config/2/sync/mask.h) \
    $(wildcard include/config/2/sync/shift.h) \
    $(wildcard include/config/2/sync/default.h) \
    $(wildcard include/config/2/polarity/mask.h) \
    $(wildcard include/config/2/polarity/shift.h) \
    $(wildcard include/config/2/polarity/default.h) \
    $(wildcard include/config/2/we/ctl/mask.h) \
    $(wildcard include/config/2/we/ctl/shift.h) \
    $(wildcard include/config/2/we/ctl/default.h) \
    $(wildcard include/config/2/dest/size/mask.h) \
    $(wildcard include/config/2/dest/size/shift.h) \
    $(wildcard include/config/2/dest/size/default.h) \
    $(wildcard include/config/2/ms/inh/mask.h) \
    $(wildcard include/config/2/ms/inh/shift.h) \
    $(wildcard include/config/2/ms/inh/default.h) \
    $(wildcard include/config/2/ls/inh/mask.h) \
    $(wildcard include/config/2/ls/inh/shift.h) \
    $(wildcard include/config/2/ls/inh/default.h) \
    $(wildcard include/config/2/bcachen/mask.h) \
    $(wildcard include/config/2/bcachen/shift.h) \
    $(wildcard include/config/2/bcachen/default.h) \
    $(wildcard include/config/2/enable/mask.h) \
    $(wildcard include/config/2/enable/shift.h) \
    $(wildcard include/config/2/enable/default.h) \
    $(wildcard include/config/3/mem/io/mask.h) \
    $(wildcard include/config/3/mem/io/shift.h) \
    $(wildcard include/config/3/mem/io/default.h) \
    $(wildcard include/config/3/ta/wait/mask.h) \
    $(wildcard include/config/3/ta/wait/shift.h) \
    $(wildcard include/config/3/ta/wait/default.h) \
    $(wildcard include/config/3/wp/mask.h) \
    $(wildcard include/config/3/wp/shift.h) \
    $(wildcard include/config/3/wp/default.h) \
    $(wildcard include/config/3/wait/count/mask.h) \
    $(wildcard include/config/3/wait/count/shift.h) \
    $(wildcard include/config/3/wait/count/default.h) \
    $(wildcard include/config/3/t/hold/mask.h) \
    $(wildcard include/config/3/t/hold/shift.h) \
    $(wildcard include/config/3/t/hold/default.h) \
    $(wildcard include/config/3/t/setup/mask.h) \
    $(wildcard include/config/3/t/setup/shift.h) \
    $(wildcard include/config/3/t/setup/default.h) \
    $(wildcard include/config/3/cs/hold/mask.h) \
    $(wildcard include/config/3/cs/hold/shift.h) \
    $(wildcard include/config/3/cs/hold/default.h) \
    $(wildcard include/config/3/split/cs/mask.h) \
    $(wildcard include/config/3/split/cs/shift.h) \
    $(wildcard include/config/3/split/cs/default.h) \
    $(wildcard include/config/3/mask/en/mask.h) \
    $(wildcard include/config/3/mask/en/shift.h) \
    $(wildcard include/config/3/mask/en/default.h) \
    $(wildcard include/config/3/ne/sample/mask.h) \
    $(wildcard include/config/3/ne/sample/shift.h) \
    $(wildcard include/config/3/ne/sample/default.h) \
    $(wildcard include/config/3/m68k/mask.h) \
    $(wildcard include/config/3/m68k/shift.h) \
    $(wildcard include/config/3/m68k/default.h) \
    $(wildcard include/config/3/le/mask.h) \
    $(wildcard include/config/3/le/shift.h) \
    $(wildcard include/config/3/le/default.h) \
    $(wildcard include/config/3/fast/read/mask.h) \
    $(wildcard include/config/3/fast/read/shift.h) \
    $(wildcard include/config/3/fast/read/default.h) \
    $(wildcard include/config/3/fast/read/normal.h) \
    $(wildcard include/config/3/fast/read/fast/read/enable.h) \
    $(wildcard include/config/3/size/sel/mask.h) \
    $(wildcard include/config/3/size/sel/shift.h) \
    $(wildcard include/config/3/size/sel/default.h) \
    $(wildcard include/config/3/sync/mask.h) \
    $(wildcard include/config/3/sync/shift.h) \
    $(wildcard include/config/3/sync/default.h) \
    $(wildcard include/config/3/polarity/mask.h) \
    $(wildcard include/config/3/polarity/shift.h) \
    $(wildcard include/config/3/polarity/default.h) \
    $(wildcard include/config/3/we/ctl/mask.h) \
    $(wildcard include/config/3/we/ctl/shift.h) \
    $(wildcard include/config/3/we/ctl/default.h) \
    $(wildcard include/config/3/dest/size/mask.h) \
    $(wildcard include/config/3/dest/size/shift.h) \
    $(wildcard include/config/3/dest/size/default.h) \
    $(wildcard include/config/3/ms/inh/mask.h) \
    $(wildcard include/config/3/ms/inh/shift.h) \
    $(wildcard include/config/3/ms/inh/default.h) \
    $(wildcard include/config/3/ls/inh/mask.h) \
    $(wildcard include/config/3/ls/inh/shift.h) \
    $(wildcard include/config/3/ls/inh/default.h) \
    $(wildcard include/config/3/bcachen/mask.h) \
    $(wildcard include/config/3/bcachen/shift.h) \
    $(wildcard include/config/3/bcachen/default.h) \
    $(wildcard include/config/3/enable/mask.h) \
    $(wildcard include/config/3/enable/shift.h) \
    $(wildcard include/config/3/enable/default.h) \
    $(wildcard include/config/4/mem/io/mask.h) \
    $(wildcard include/config/4/mem/io/shift.h) \
    $(wildcard include/config/4/mem/io/default.h) \
    $(wildcard include/config/4/ta/wait/mask.h) \
    $(wildcard include/config/4/ta/wait/shift.h) \
    $(wildcard include/config/4/ta/wait/default.h) \
    $(wildcard include/config/4/wp/mask.h) \
    $(wildcard include/config/4/wp/shift.h) \
    $(wildcard include/config/4/wp/default.h) \
    $(wildcard include/config/4/wait/count/mask.h) \
    $(wildcard include/config/4/wait/count/shift.h) \
    $(wildcard include/config/4/wait/count/default.h) \
    $(wildcard include/config/4/t/hold/mask.h) \
    $(wildcard include/config/4/t/hold/shift.h) \
    $(wildcard include/config/4/t/hold/default.h) \
    $(wildcard include/config/4/t/setup/mask.h) \
    $(wildcard include/config/4/t/setup/shift.h) \
    $(wildcard include/config/4/t/setup/default.h) \
    $(wildcard include/config/4/cs/hold/mask.h) \
    $(wildcard include/config/4/cs/hold/shift.h) \
    $(wildcard include/config/4/cs/hold/default.h) \
    $(wildcard include/config/4/split/cs/mask.h) \
    $(wildcard include/config/4/split/cs/shift.h) \
    $(wildcard include/config/4/split/cs/default.h) \
    $(wildcard include/config/4/mask/en/mask.h) \
    $(wildcard include/config/4/mask/en/shift.h) \
    $(wildcard include/config/4/mask/en/default.h) \
    $(wildcard include/config/4/ne/sample/mask.h) \
    $(wildcard include/config/4/ne/sample/shift.h) \
    $(wildcard include/config/4/ne/sample/default.h) \
    $(wildcard include/config/4/m68k/mask.h) \
    $(wildcard include/config/4/m68k/shift.h) \
    $(wildcard include/config/4/m68k/default.h) \
    $(wildcard include/config/4/le/mask.h) \
    $(wildcard include/config/4/le/shift.h) \
    $(wildcard include/config/4/le/default.h) \
    $(wildcard include/config/4/fast/read/mask.h) \
    $(wildcard include/config/4/fast/read/shift.h) \
    $(wildcard include/config/4/fast/read/default.h) \
    $(wildcard include/config/4/fast/read/normal.h) \
    $(wildcard include/config/4/fast/read/fast/read/enable.h) \
    $(wildcard include/config/4/size/sel/mask.h) \
    $(wildcard include/config/4/size/sel/shift.h) \
    $(wildcard include/config/4/size/sel/default.h) \
    $(wildcard include/config/4/sync/mask.h) \
    $(wildcard include/config/4/sync/shift.h) \
    $(wildcard include/config/4/sync/default.h) \
    $(wildcard include/config/4/polarity/mask.h) \
    $(wildcard include/config/4/polarity/shift.h) \
    $(wildcard include/config/4/polarity/default.h) \
    $(wildcard include/config/4/we/ctl/mask.h) \
    $(wildcard include/config/4/we/ctl/shift.h) \
    $(wildcard include/config/4/we/ctl/default.h) \
    $(wildcard include/config/4/dest/size/mask.h) \
    $(wildcard include/config/4/dest/size/shift.h) \
    $(wildcard include/config/4/dest/size/default.h) \
    $(wildcard include/config/4/ms/inh/mask.h) \
    $(wildcard include/config/4/ms/inh/shift.h) \
    $(wildcard include/config/4/ms/inh/default.h) \
    $(wildcard include/config/4/ls/inh/mask.h) \
    $(wildcard include/config/4/ls/inh/shift.h) \
    $(wildcard include/config/4/ls/inh/default.h) \
    $(wildcard include/config/4/bcachen/mask.h) \
    $(wildcard include/config/4/bcachen/shift.h) \
    $(wildcard include/config/4/bcachen/default.h) \
    $(wildcard include/config/4/enable/mask.h) \
    $(wildcard include/config/4/enable/shift.h) \
    $(wildcard include/config/4/enable/default.h) \
    $(wildcard include/config/5/mem/io/mask.h) \
    $(wildcard include/config/5/mem/io/shift.h) \
    $(wildcard include/config/5/mem/io/default.h) \
    $(wildcard include/config/5/ta/wait/mask.h) \
    $(wildcard include/config/5/ta/wait/shift.h) \
    $(wildcard include/config/5/ta/wait/default.h) \
    $(wildcard include/config/5/wp/mask.h) \
    $(wildcard include/config/5/wp/shift.h) \
    $(wildcard include/config/5/wp/default.h) \
    $(wildcard include/config/5/wait/count/mask.h) \
    $(wildcard include/config/5/wait/count/shift.h) \
    $(wildcard include/config/5/wait/count/default.h) \
    $(wildcard include/config/5/t/hold/mask.h) \
    $(wildcard include/config/5/t/hold/shift.h) \
    $(wildcard include/config/5/t/hold/default.h) \
    $(wildcard include/config/5/t/setup/mask.h) \
    $(wildcard include/config/5/t/setup/shift.h) \
    $(wildcard include/config/5/t/setup/default.h) \
    $(wildcard include/config/5/cs/hold/mask.h) \
    $(wildcard include/config/5/cs/hold/shift.h) \
    $(wildcard include/config/5/cs/hold/default.h) \
    $(wildcard include/config/5/split/cs/mask.h) \
    $(wildcard include/config/5/split/cs/shift.h) \
    $(wildcard include/config/5/split/cs/default.h) \
    $(wildcard include/config/5/mask/en/mask.h) \
    $(wildcard include/config/5/mask/en/shift.h) \
    $(wildcard include/config/5/mask/en/default.h) \
    $(wildcard include/config/5/ne/sample/mask.h) \
    $(wildcard include/config/5/ne/sample/shift.h) \
    $(wildcard include/config/5/ne/sample/default.h) \
    $(wildcard include/config/5/m68k/mask.h) \
    $(wildcard include/config/5/m68k/shift.h) \
    $(wildcard include/config/5/m68k/default.h) \
    $(wildcard include/config/5/le/mask.h) \
    $(wildcard include/config/5/le/shift.h) \
    $(wildcard include/config/5/le/default.h) \
    $(wildcard include/config/5/fast/read/mask.h) \
    $(wildcard include/config/5/fast/read/shift.h) \
    $(wildcard include/config/5/fast/read/default.h) \
    $(wildcard include/config/5/fast/read/normal.h) \
    $(wildcard include/config/5/fast/read/fast/read/enable.h) \
    $(wildcard include/config/5/size/sel/mask.h) \
    $(wildcard include/config/5/size/sel/shift.h) \
    $(wildcard include/config/5/size/sel/default.h) \
    $(wildcard include/config/5/sync/mask.h) \
    $(wildcard include/config/5/sync/shift.h) \
    $(wildcard include/config/5/sync/default.h) \
    $(wildcard include/config/5/polarity/mask.h) \
    $(wildcard include/config/5/polarity/shift.h) \
    $(wildcard include/config/5/polarity/default.h) \
    $(wildcard include/config/5/we/ctl/mask.h) \
    $(wildcard include/config/5/we/ctl/shift.h) \
    $(wildcard include/config/5/we/ctl/default.h) \
    $(wildcard include/config/5/dest/size/mask.h) \
    $(wildcard include/config/5/dest/size/shift.h) \
    $(wildcard include/config/5/dest/size/default.h) \
    $(wildcard include/config/5/ms/inh/mask.h) \
    $(wildcard include/config/5/ms/inh/shift.h) \
    $(wildcard include/config/5/ms/inh/default.h) \
    $(wildcard include/config/5/ls/inh/mask.h) \
    $(wildcard include/config/5/ls/inh/shift.h) \
    $(wildcard include/config/5/ls/inh/default.h) \
    $(wildcard include/config/5/bcachen/mask.h) \
    $(wildcard include/config/5/bcachen/shift.h) \
    $(wildcard include/config/5/bcachen/default.h) \
    $(wildcard include/config/5/enable/mask.h) \
    $(wildcard include/config/5/enable/shift.h) \
    $(wildcard include/config/5/enable/default.h) \
  include/linux/brcmstb/7435b0/bchp_edu.h \
    $(wildcard include/config/swap/mask.h) \
    $(wildcard include/config/swap/shift.h) \
    $(wildcard include/config/swap/default.h) \
    $(wildcard include/config/mode/mask.h) \
    $(wildcard include/config/mode/shift.h) \
    $(wildcard include/config/mode/default.h) \
  include/linux/brcmstb/7435b0/bchp_flash_dma.h \
  include/linux/brcmstb/7435b0/bchp_gio.h \
  include/linux/brcmstb/7435b0/bchp_gio_aon.h \
  include/linux/brcmstb/7435b0/bchp_hif_cpu_intr1.h \
  include/linux/brcmstb/7435b0/bchp_hif_cpu_tp1_intr1.h \
  include/linux/brcmstb/7435b0/bchp_hif_intr2.h \
  include/linux/brcmstb/7435b0/bchp_hif_mspi.h \
  include/linux/brcmstb/7435b0/bchp_hif_rgr1.h \
  include/linux/brcmstb/7435b0/bchp_hif_spi_intr2.h \
  include/linux/brcmstb/7435b0/bchp_hif_top_ctrl.h \
  include/linux/brcmstb/7435b0/bchp_irq0.h \
  include/linux/brcmstb/7435b0/bchp_irq1.h \
  include/linux/brcmstb/7435b0/bchp_mem_dma_0.h \
  include/linux/brcmstb/7435b0/bchp_memc_arb_1.h \
  include/linux/brcmstb/7435b0/bchp_memc_ddr23_shim_addr_cntl_0.h \
    $(wildcard include/config/last/rd/stretch/mask.h) \
    $(wildcard include/config/last/rd/stretch/shift.h) \
    $(wildcard include/config/last/rd/stretch/default.h) \
    $(wildcard include/config/odt/latency/mask.h) \
    $(wildcard include/config/odt/latency/shift.h) \
    $(wildcard include/config/odt/latency/default.h) \
    $(wildcard include/config/last/read/latency/mask.h) \
    $(wildcard include/config/last/read/latency/shift.h) \
    $(wildcard include/config/last/read/latency/default.h) \
    $(wildcard include/config/read/latency/mask.h) \
    $(wildcard include/config/read/latency/shift.h) \
    $(wildcard include/config/read/latency/default.h) \
    $(wildcard include/config/write/latency/mask.h) \
    $(wildcard include/config/write/latency/shift.h) \
    $(wildcard include/config/write/latency/default.h) \
    $(wildcard include/config/dram/width/mask.h) \
    $(wildcard include/config/dram/width/shift.h) \
    $(wildcard include/config/dram/width/default.h) \
    $(wildcard include/config/ddr/mode/mask.h) \
    $(wildcard include/config/ddr/mode/shift.h) \
    $(wildcard include/config/ddr/mode/default.h) \
    $(wildcard include/config/odt/tie/high/mask.h) \
    $(wildcard include/config/odt/tie/high/shift.h) \
    $(wildcard include/config/odt/tie/high/default.h) \
    $(wildcard include/config/odt/enable/mask.h) \
    $(wildcard include/config/odt/enable/shift.h) \
    $(wildcard include/config/odt/enable/default.h) \
    $(wildcard include/config/stretch/mask.h) \
    $(wildcard include/config/stretch/shift.h) \
    $(wildcard include/config/stretch/default.h) \
    $(wildcard include/config/early/mask.h) \
    $(wildcard include/config/early/shift.h) \
    $(wildcard include/config/early/default.h) \
    $(wildcard include/config/delay/mask.h) \
    $(wildcard include/config/delay/shift.h) \
    $(wildcard include/config/delay/default.h) \
  include/linux/brcmstb/7435b0/bchp_memc_ddr23_shim_addr_cntl_1.h \
  include/linux/brcmstb/7435b0/bchp_memc_ddr_0.h \
    $(wildcard include/config/device/tech/mask.h) \
    $(wildcard include/config/device/tech/shift.h) \
    $(wildcard include/config/device/tech/default.h) \
    $(wildcard include/config/ppd/en/mask.h) \
    $(wildcard include/config/ppd/en/shift.h) \
    $(wildcard include/config/ppd/en/default.h) \
    $(wildcard include/config/inact/count/mask.h) \
    $(wildcard include/config/inact/count/shift.h) \
    $(wildcard include/config/inact/count/default.h) \
    $(wildcard include/config/srpd/en/mask.h) \
    $(wildcard include/config/srpd/en/shift.h) \
    $(wildcard include/config/srpd/en/default.h) \
  include/linux/brcmstb/7435b0/bchp_memc_ddr_1.h \
  include/linux/brcmstb/7435b0/bchp_memc_misc_1.h \
    $(wildcard include/config/ddr/config/mask.h) \
    $(wildcard include/config/mask.h) \
    $(wildcard include/config/ddr/config/shift.h) \
    $(wildcard include/config/shift.h) \
    $(wildcard include/config/ddr/config/default.h) \
    $(wildcard include/config/default.h) \
    $(wildcard include/config/ddr/config/ddr32bit.h) \
    $(wildcard include/config/ddr32bit.h) \
    $(wildcard include/config/ddr/config/ddr16bit.h) \
    $(wildcard include/config/ddr16bit.h) \
  include/linux/brcmstb/7435b0/bchp_moca_hostmisc.h \
  include/linux/brcmstb/7435b0/bchp_nand.h \
    $(wildcard include/config/cs0.h) \
    $(wildcard include/config/cs1.h) \
    $(wildcard include/config/cs2.h) \
    $(wildcard include/config/cs3.h) \
    $(wildcard include/config/cs4.h) \
    $(wildcard include/config/cs5.h) \
    $(wildcard include/config/lock.h) \
    $(wildcard include/config/cs0/config/lock/mask.h) \
    $(wildcard include/config/lock/mask.h) \
    $(wildcard include/config/cs0/config/lock/shift.h) \
    $(wildcard include/config/lock/shift.h) \
    $(wildcard include/config/cs0/config/lock/default.h) \
    $(wildcard include/config/lock/default.h) \
    $(wildcard include/config/cs0/block/size/mask.h) \
    $(wildcard include/config/cs0/block/size/shift.h) \
    $(wildcard include/config/cs0/block/size/bk/size/2048kb.h) \
    $(wildcard include/config/cs0/block/size/bk/size/1024kb.h) \
    $(wildcard include/config/cs0/block/size/bk/size/512kb.h) \
    $(wildcard include/config/cs0/block/size/bk/size/256kb.h) \
    $(wildcard include/config/cs0/block/size/bk/size/128kb.h) \
    $(wildcard include/config/cs0/block/size/bk/size/16kb.h) \
    $(wildcard include/config/cs0/block/size/bk/size/8kb.h) \
    $(wildcard include/config/cs0/device/size/mask.h) \
    $(wildcard include/config/cs0/device/size/shift.h) \
    $(wildcard include/config/cs0/device/size/dvc/size/4mb.h) \
    $(wildcard include/config/cs0/device/size/dvc/size/8mb.h) \
    $(wildcard include/config/cs0/device/size/dvc/size/16mb.h) \
    $(wildcard include/config/cs0/device/size/dvc/size/32mb.h) \
    $(wildcard include/config/cs0/device/size/dvc/size/64mb.h) \
    $(wildcard include/config/cs0/device/size/dvc/size/128mb.h) \
    $(wildcard include/config/cs0/device/size/dvc/size/256mb.h) \
    $(wildcard include/config/cs0/device/size/dvc/size/512mb.h) \
    $(wildcard include/config/cs0/device/size/dvc/size/1gb.h) \
    $(wildcard include/config/cs0/device/size/dvc/size/2gb.h) \
    $(wildcard include/config/cs0/device/size/dvc/size/4gb.h) \
    $(wildcard include/config/cs0/device/size/dvc/size/8gb.h) \
    $(wildcard include/config/cs0/device/size/dvc/size/16gb.h) \
    $(wildcard include/config/cs0/device/size/dvc/size/32gb.h) \
    $(wildcard include/config/cs0/device/size/dvc/size/64gb.h) \
    $(wildcard include/config/cs0/device/size/dvc/size/128gb.h) \
    $(wildcard include/config/cs0/device/width/mask.h) \
    $(wildcard include/config/cs0/device/width/shift.h) \
    $(wildcard include/config/cs0/device/width/dvc/width/8.h) \
    $(wildcard include/config/cs0/device/width/dvc/width/16.h) \
    $(wildcard include/config/cs0/reserved0/mask.h) \
    $(wildcard include/config/cs0/reserved0/shift.h) \
    $(wildcard include/config/cs0/page/size/mask.h) \
    $(wildcard include/config/cs0/page/size/shift.h) \
    $(wildcard include/config/cs0/page/size/pg/size/512.h) \
    $(wildcard include/config/cs0/page/size/pg/size/2kb.h) \
    $(wildcard include/config/cs0/page/size/pg/size/4kb.h) \
    $(wildcard include/config/cs0/page/size/pg/size/8kb.h) \
    $(wildcard include/config/cs0/reserved1/mask.h) \
    $(wildcard include/config/cs0/reserved1/shift.h) \
    $(wildcard include/config/cs0/ful/adr/bytes/mask.h) \
    $(wildcard include/config/cs0/ful/adr/bytes/shift.h) \
    $(wildcard include/config/cs0/reserved2/mask.h) \
    $(wildcard include/config/cs0/reserved2/shift.h) \
    $(wildcard include/config/cs0/col/adr/bytes/mask.h) \
    $(wildcard include/config/cs0/col/adr/bytes/shift.h) \
    $(wildcard include/config/cs0/reserved3/mask.h) \
    $(wildcard include/config/cs0/reserved3/shift.h) \
    $(wildcard include/config/cs0/blk/adr/bytes/mask.h) \
    $(wildcard include/config/cs0/blk/adr/bytes/shift.h) \
    $(wildcard include/config/cs0/reserved4/mask.h) \
    $(wildcard include/config/cs0/reserved4/shift.h) \
    $(wildcard include/config/cs1/config/lock/mask.h) \
    $(wildcard include/config/cs1/config/lock/shift.h) \
    $(wildcard include/config/cs1/config/lock/default.h) \
    $(wildcard include/config/cs1/block/size/mask.h) \
    $(wildcard include/config/cs1/block/size/shift.h) \
    $(wildcard include/config/cs1/block/size/bk/size/2048kb.h) \
    $(wildcard include/config/cs1/block/size/bk/size/1024kb.h) \
    $(wildcard include/config/cs1/block/size/bk/size/512kb.h) \
    $(wildcard include/config/cs1/block/size/bk/size/256kb.h) \
    $(wildcard include/config/cs1/block/size/bk/size/128kb.h) \
    $(wildcard include/config/cs1/block/size/bk/size/16kb.h) \
    $(wildcard include/config/cs1/block/size/bk/size/8kb.h) \
    $(wildcard include/config/cs1/device/size/mask.h) \
    $(wildcard include/config/cs1/device/size/shift.h) \
    $(wildcard include/config/cs1/device/size/dvc/size/4mb.h) \
    $(wildcard include/config/cs1/device/size/dvc/size/8mb.h) \
    $(wildcard include/config/cs1/device/size/dvc/size/16mb.h) \
    $(wildcard include/config/cs1/device/size/dvc/size/32mb.h) \
    $(wildcard include/config/cs1/device/size/dvc/size/64mb.h) \
    $(wildcard include/config/cs1/device/size/dvc/size/128mb.h) \
    $(wildcard include/config/cs1/device/size/dvc/size/256mb.h) \
    $(wildcard include/config/cs1/device/size/dvc/size/512mb.h) \
    $(wildcard include/config/cs1/device/size/dvc/size/1gb.h) \
    $(wildcard include/config/cs1/device/size/dvc/size/2gb.h) \
    $(wildcard include/config/cs1/device/size/dvc/size/4gb.h) \
    $(wildcard include/config/cs1/device/size/dvc/size/8gb.h) \
    $(wildcard include/config/cs1/device/size/dvc/size/16gb.h) \
    $(wildcard include/config/cs1/device/size/dvc/size/32gb.h) \
    $(wildcard include/config/cs1/device/size/dvc/size/64gb.h) \
    $(wildcard include/config/cs1/device/size/dvc/size/128gb.h) \
    $(wildcard include/config/cs1/device/width/mask.h) \
    $(wildcard include/config/cs1/device/width/shift.h) \
    $(wildcard include/config/cs1/device/width/dvc/width/8.h) \
    $(wildcard include/config/cs1/device/width/dvc/width/16.h) \
    $(wildcard include/config/cs1/reserved0/mask.h) \
    $(wildcard include/config/cs1/reserved0/shift.h) \
    $(wildcard include/config/cs1/page/size/mask.h) \
    $(wildcard include/config/cs1/page/size/shift.h) \
    $(wildcard include/config/cs1/page/size/pg/size/512.h) \
    $(wildcard include/config/cs1/page/size/pg/size/2kb.h) \
    $(wildcard include/config/cs1/page/size/pg/size/4kb.h) \
    $(wildcard include/config/cs1/page/size/pg/size/8kb.h) \
    $(wildcard include/config/cs1/reserved1/mask.h) \
    $(wildcard include/config/cs1/reserved1/shift.h) \
    $(wildcard include/config/cs1/ful/adr/bytes/mask.h) \
    $(wildcard include/config/cs1/ful/adr/bytes/shift.h) \
    $(wildcard include/config/cs1/reserved2/mask.h) \
    $(wildcard include/config/cs1/reserved2/shift.h) \
    $(wildcard include/config/cs1/col/adr/bytes/mask.h) \
    $(wildcard include/config/cs1/col/adr/bytes/shift.h) \
    $(wildcard include/config/cs1/reserved3/mask.h) \
    $(wildcard include/config/cs1/reserved3/shift.h) \
    $(wildcard include/config/cs1/blk/adr/bytes/mask.h) \
    $(wildcard include/config/cs1/blk/adr/bytes/shift.h) \
    $(wildcard include/config/cs1/reserved4/mask.h) \
    $(wildcard include/config/cs1/reserved4/shift.h) \
    $(wildcard include/config/cs2/config/lock/mask.h) \
    $(wildcard include/config/cs2/config/lock/shift.h) \
    $(wildcard include/config/cs2/config/lock/default.h) \
    $(wildcard include/config/cs2/block/size/mask.h) \
    $(wildcard include/config/cs2/block/size/shift.h) \
    $(wildcard include/config/cs2/block/size/bk/size/2048kb.h) \
    $(wildcard include/config/cs2/block/size/bk/size/1024kb.h) \
    $(wildcard include/config/cs2/block/size/bk/size/512kb.h) \
    $(wildcard include/config/cs2/block/size/bk/size/256kb.h) \
    $(wildcard include/config/cs2/block/size/bk/size/128kb.h) \
    $(wildcard include/config/cs2/block/size/bk/size/16kb.h) \
    $(wildcard include/config/cs2/block/size/bk/size/8kb.h) \
    $(wildcard include/config/cs2/device/size/mask.h) \
    $(wildcard include/config/cs2/device/size/shift.h) \
    $(wildcard include/config/cs2/device/size/dvc/size/4mb.h) \
    $(wildcard include/config/cs2/device/size/dvc/size/8mb.h) \
    $(wildcard include/config/cs2/device/size/dvc/size/16mb.h) \
    $(wildcard include/config/cs2/device/size/dvc/size/32mb.h) \
    $(wildcard include/config/cs2/device/size/dvc/size/64mb.h) \
    $(wildcard include/config/cs2/device/size/dvc/size/128mb.h) \
    $(wildcard include/config/cs2/device/size/dvc/size/256mb.h) \
    $(wildcard include/config/cs2/device/size/dvc/size/512mb.h) \
    $(wildcard include/config/cs2/device/size/dvc/size/1gb.h) \
    $(wildcard include/config/cs2/device/size/dvc/size/2gb.h) \
    $(wildcard include/config/cs2/device/size/dvc/size/4gb.h) \
    $(wildcard include/config/cs2/device/size/dvc/size/8gb.h) \
    $(wildcard include/config/cs2/device/size/dvc/size/16gb.h) \
    $(wildcard include/config/cs2/device/size/dvc/size/32gb.h) \
    $(wildcard include/config/cs2/device/size/dvc/size/64gb.h) \
    $(wildcard include/config/cs2/device/size/dvc/size/128gb.h) \
    $(wildcard include/config/cs2/device/width/mask.h) \
    $(wildcard include/config/cs2/device/width/shift.h) \
    $(wildcard include/config/cs2/device/width/dvc/width/8.h) \
    $(wildcard include/config/cs2/device/width/dvc/width/16.h) \
    $(wildcard include/config/cs2/reserved0/mask.h) \
    $(wildcard include/config/cs2/reserved0/shift.h) \
    $(wildcard include/config/cs2/page/size/mask.h) \
    $(wildcard include/config/cs2/page/size/shift.h) \
    $(wildcard include/config/cs2/page/size/pg/size/512.h) \
    $(wildcard include/config/cs2/page/size/pg/size/2kb.h) \
    $(wildcard include/config/cs2/page/size/pg/size/4kb.h) \
    $(wildcard include/config/cs2/page/size/pg/size/8kb.h) \
    $(wildcard include/config/cs2/reserved1/mask.h) \
    $(wildcard include/config/cs2/reserved1/shift.h) \
    $(wildcard include/config/cs2/ful/adr/bytes/mask.h) \
    $(wildcard include/config/cs2/ful/adr/bytes/shift.h) \
    $(wildcard include/config/cs2/reserved2/mask.h) \
    $(wildcard include/config/cs2/reserved2/shift.h) \
    $(wildcard include/config/cs2/col/adr/bytes/mask.h) \
    $(wildcard include/config/cs2/col/adr/bytes/shift.h) \
    $(wildcard include/config/cs2/reserved3/mask.h) \
    $(wildcard include/config/cs2/reserved3/shift.h) \
    $(wildcard include/config/cs2/blk/adr/bytes/mask.h) \
    $(wildcard include/config/cs2/blk/adr/bytes/shift.h) \
    $(wildcard include/config/cs2/reserved4/mask.h) \
    $(wildcard include/config/cs2/reserved4/shift.h) \
    $(wildcard include/config/cs3/config/lock/mask.h) \
    $(wildcard include/config/cs3/config/lock/shift.h) \
    $(wildcard include/config/cs3/config/lock/default.h) \
    $(wildcard include/config/cs3/block/size/mask.h) \
    $(wildcard include/config/cs3/block/size/shift.h) \
    $(wildcard include/config/cs3/block/size/bk/size/2048kb.h) \
    $(wildcard include/config/cs3/block/size/bk/size/1024kb.h) \
    $(wildcard include/config/cs3/block/size/bk/size/512kb.h) \
    $(wildcard include/config/cs3/block/size/bk/size/256kb.h) \
    $(wildcard include/config/cs3/block/size/bk/size/128kb.h) \
    $(wildcard include/config/cs3/block/size/bk/size/16kb.h) \
    $(wildcard include/config/cs3/block/size/bk/size/8kb.h) \
    $(wildcard include/config/cs3/device/size/mask.h) \
    $(wildcard include/config/cs3/device/size/shift.h) \
    $(wildcard include/config/cs3/device/size/dvc/size/4mb.h) \
    $(wildcard include/config/cs3/device/size/dvc/size/8mb.h) \
    $(wildcard include/config/cs3/device/size/dvc/size/16mb.h) \
    $(wildcard include/config/cs3/device/size/dvc/size/32mb.h) \
    $(wildcard include/config/cs3/device/size/dvc/size/64mb.h) \
    $(wildcard include/config/cs3/device/size/dvc/size/128mb.h) \
    $(wildcard include/config/cs3/device/size/dvc/size/256mb.h) \
    $(wildcard include/config/cs3/device/size/dvc/size/512mb.h) \
    $(wildcard include/config/cs3/device/size/dvc/size/1gb.h) \
    $(wildcard include/config/cs3/device/size/dvc/size/2gb.h) \
    $(wildcard include/config/cs3/device/size/dvc/size/4gb.h) \
    $(wildcard include/config/cs3/device/size/dvc/size/8gb.h) \
    $(wildcard include/config/cs3/device/size/dvc/size/16gb.h) \
    $(wildcard include/config/cs3/device/size/dvc/size/32gb.h) \
    $(wildcard include/config/cs3/device/size/dvc/size/64gb.h) \
    $(wildcard include/config/cs3/device/size/dvc/size/128gb.h) \
    $(wildcard include/config/cs3/device/width/mask.h) \
    $(wildcard include/config/cs3/device/width/shift.h) \
    $(wildcard include/config/cs3/device/width/dvc/width/8.h) \
    $(wildcard include/config/cs3/device/width/dvc/width/16.h) \
    $(wildcard include/config/cs3/reserved0/mask.h) \
    $(wildcard include/config/cs3/reserved0/shift.h) \
    $(wildcard include/config/cs3/page/size/mask.h) \
    $(wildcard include/config/cs3/page/size/shift.h) \
    $(wildcard include/config/cs3/page/size/pg/size/512.h) \
    $(wildcard include/config/cs3/page/size/pg/size/2kb.h) \
    $(wildcard include/config/cs3/page/size/pg/size/4kb.h) \
    $(wildcard include/config/cs3/page/size/pg/size/8kb.h) \
    $(wildcard include/config/cs3/reserved1/mask.h) \
    $(wildcard include/config/cs3/reserved1/shift.h) \
    $(wildcard include/config/cs3/ful/adr/bytes/mask.h) \
    $(wildcard include/config/cs3/ful/adr/bytes/shift.h) \
    $(wildcard include/config/cs3/reserved2/mask.h) \
    $(wildcard include/config/cs3/reserved2/shift.h) \
    $(wildcard include/config/cs3/col/adr/bytes/mask.h) \
    $(wildcard include/config/cs3/col/adr/bytes/shift.h) \
    $(wildcard include/config/cs3/reserved3/mask.h) \
    $(wildcard include/config/cs3/reserved3/shift.h) \
    $(wildcard include/config/cs3/blk/adr/bytes/mask.h) \
    $(wildcard include/config/cs3/blk/adr/bytes/shift.h) \
    $(wildcard include/config/cs3/reserved4/mask.h) \
    $(wildcard include/config/cs3/reserved4/shift.h) \
    $(wildcard include/config/cs4/config/lock/mask.h) \
    $(wildcard include/config/cs4/config/lock/shift.h) \
    $(wildcard include/config/cs4/config/lock/default.h) \
    $(wildcard include/config/cs4/block/size/mask.h) \
    $(wildcard include/config/cs4/block/size/shift.h) \
    $(wildcard include/config/cs4/block/size/bk/size/2048kb.h) \
    $(wildcard include/config/cs4/block/size/bk/size/1024kb.h) \
    $(wildcard include/config/cs4/block/size/bk/size/512kb.h) \
    $(wildcard include/config/cs4/block/size/bk/size/256kb.h) \
    $(wildcard include/config/cs4/block/size/bk/size/128kb.h) \
    $(wildcard include/config/cs4/block/size/bk/size/16kb.h) \
    $(wildcard include/config/cs4/block/size/bk/size/8kb.h) \
    $(wildcard include/config/cs4/device/size/mask.h) \
    $(wildcard include/config/cs4/device/size/shift.h) \
    $(wildcard include/config/cs4/device/size/dvc/size/4mb.h) \
    $(wildcard include/config/cs4/device/size/dvc/size/8mb.h) \
    $(wildcard include/config/cs4/device/size/dvc/size/16mb.h) \
    $(wildcard include/config/cs4/device/size/dvc/size/32mb.h) \
    $(wildcard include/config/cs4/device/size/dvc/size/64mb.h) \
    $(wildcard include/config/cs4/device/size/dvc/size/128mb.h) \
    $(wildcard include/config/cs4/device/size/dvc/size/256mb.h) \
    $(wildcard include/config/cs4/device/size/dvc/size/512mb.h) \
    $(wildcard include/config/cs4/device/size/dvc/size/1gb.h) \
    $(wildcard include/config/cs4/device/size/dvc/size/2gb.h) \
    $(wildcard include/config/cs4/device/size/dvc/size/4gb.h) \
    $(wildcard include/config/cs4/device/size/dvc/size/8gb.h) \
    $(wildcard include/config/cs4/device/size/dvc/size/16gb.h) \
    $(wildcard include/config/cs4/device/size/dvc/size/32gb.h) \
    $(wildcard include/config/cs4/device/size/dvc/size/64gb.h) \
    $(wildcard include/config/cs4/device/size/dvc/size/128gb.h) \
    $(wildcard include/config/cs4/device/width/mask.h) \
    $(wildcard include/config/cs4/device/width/shift.h) \
    $(wildcard include/config/cs4/device/width/dvc/width/8.h) \
    $(wildcard include/config/cs4/device/width/dvc/width/16.h) \
    $(wildcard include/config/cs4/reserved0/mask.h) \
    $(wildcard include/config/cs4/reserved0/shift.h) \
    $(wildcard include/config/cs4/page/size/mask.h) \
    $(wildcard include/config/cs4/page/size/shift.h) \
    $(wildcard include/config/cs4/page/size/pg/size/512.h) \
    $(wildcard include/config/cs4/page/size/pg/size/2kb.h) \
    $(wildcard include/config/cs4/page/size/pg/size/4kb.h) \
    $(wildcard include/config/cs4/page/size/pg/size/8kb.h) \
    $(wildcard include/config/cs4/reserved1/mask.h) \
    $(wildcard include/config/cs4/reserved1/shift.h) \
    $(wildcard include/config/cs4/ful/adr/bytes/mask.h) \
    $(wildcard include/config/cs4/ful/adr/bytes/shift.h) \
    $(wildcard include/config/cs4/reserved2/mask.h) \
    $(wildcard include/config/cs4/reserved2/shift.h) \
    $(wildcard include/config/cs4/col/adr/bytes/mask.h) \
    $(wildcard include/config/cs4/col/adr/bytes/shift.h) \
    $(wildcard include/config/cs4/reserved3/mask.h) \
    $(wildcard include/config/cs4/reserved3/shift.h) \
    $(wildcard include/config/cs4/blk/adr/bytes/mask.h) \
    $(wildcard include/config/cs4/blk/adr/bytes/shift.h) \
    $(wildcard include/config/cs4/reserved4/mask.h) \
    $(wildcard include/config/cs4/reserved4/shift.h) \
    $(wildcard include/config/cs5/config/lock/mask.h) \
    $(wildcard include/config/cs5/config/lock/shift.h) \
    $(wildcard include/config/cs5/config/lock/default.h) \
    $(wildcard include/config/cs5/block/size/mask.h) \
    $(wildcard include/config/cs5/block/size/shift.h) \
    $(wildcard include/config/cs5/block/size/bk/size/2048kb.h) \
    $(wildcard include/config/cs5/block/size/bk/size/1024kb.h) \
    $(wildcard include/config/cs5/block/size/bk/size/512kb.h) \
    $(wildcard include/config/cs5/block/size/bk/size/256kb.h) \
    $(wildcard include/config/cs5/block/size/bk/size/128kb.h) \
    $(wildcard include/config/cs5/block/size/bk/size/16kb.h) \
    $(wildcard include/config/cs5/block/size/bk/size/8kb.h) \
    $(wildcard include/config/cs5/device/size/mask.h) \
    $(wildcard include/config/cs5/device/size/shift.h) \
    $(wildcard include/config/cs5/device/size/dvc/size/4mb.h) \
    $(wildcard include/config/cs5/device/size/dvc/size/8mb.h) \
    $(wildcard include/config/cs5/device/size/dvc/size/16mb.h) \
    $(wildcard include/config/cs5/device/size/dvc/size/32mb.h) \
    $(wildcard include/config/cs5/device/size/dvc/size/64mb.h) \
    $(wildcard include/config/cs5/device/size/dvc/size/128mb.h) \
    $(wildcard include/config/cs5/device/size/dvc/size/256mb.h) \
    $(wildcard include/config/cs5/device/size/dvc/size/512mb.h) \
    $(wildcard include/config/cs5/device/size/dvc/size/1gb.h) \
    $(wildcard include/config/cs5/device/size/dvc/size/2gb.h) \
    $(wildcard include/config/cs5/device/size/dvc/size/4gb.h) \
    $(wildcard include/config/cs5/device/size/dvc/size/8gb.h) \
    $(wildcard include/config/cs5/device/size/dvc/size/16gb.h) \
    $(wildcard include/config/cs5/device/size/dvc/size/32gb.h) \
    $(wildcard include/config/cs5/device/size/dvc/size/64gb.h) \
    $(wildcard include/config/cs5/device/size/dvc/size/128gb.h) \
    $(wildcard include/config/cs5/device/width/mask.h) \
    $(wildcard include/config/cs5/device/width/shift.h) \
    $(wildcard include/config/cs5/device/width/dvc/width/8.h) \
    $(wildcard include/config/cs5/device/width/dvc/width/16.h) \
    $(wildcard include/config/cs5/reserved0/mask.h) \
    $(wildcard include/config/cs5/reserved0/shift.h) \
    $(wildcard include/config/cs5/page/size/mask.h) \
    $(wildcard include/config/cs5/page/size/shift.h) \
    $(wildcard include/config/cs5/page/size/pg/size/512.h) \
    $(wildcard include/config/cs5/page/size/pg/size/2kb.h) \
    $(wildcard include/config/cs5/page/size/pg/size/4kb.h) \
    $(wildcard include/config/cs5/page/size/pg/size/8kb.h) \
    $(wildcard include/config/cs5/reserved1/mask.h) \
    $(wildcard include/config/cs5/reserved1/shift.h) \
    $(wildcard include/config/cs5/ful/adr/bytes/mask.h) \
    $(wildcard include/config/cs5/ful/adr/bytes/shift.h) \
    $(wildcard include/config/cs5/reserved2/mask.h) \
    $(wildcard include/config/cs5/reserved2/shift.h) \
    $(wildcard include/config/cs5/col/adr/bytes/mask.h) \
    $(wildcard include/config/cs5/col/adr/bytes/shift.h) \
    $(wildcard include/config/cs5/reserved3/mask.h) \
    $(wildcard include/config/cs5/reserved3/shift.h) \
    $(wildcard include/config/cs5/blk/adr/bytes/mask.h) \
    $(wildcard include/config/cs5/blk/adr/bytes/shift.h) \
    $(wildcard include/config/cs5/reserved4/mask.h) \
    $(wildcard include/config/cs5/reserved4/shift.h) \
  include/linux/brcmstb/7435b0/bchp_pcie_dma.h \
  include/linux/brcmstb/7435b0/bchp_pcie_ext_cfg.h \
  include/linux/brcmstb/7435b0/bchp_pcie_intr2.h \
  include/linux/brcmstb/7435b0/bchp_pcie_misc.h \
    $(wildcard include/config/lo.h) \
    $(wildcard include/config/hi.h) \
    $(wildcard include/config/retry/timeout.h) \
    $(wildcard include/config/remap.h) \
    $(wildcard include/config/lo/match/address/mask.h) \
    $(wildcard include/config/lo/match/address/shift.h) \
    $(wildcard include/config/lo/match/address/default.h) \
    $(wildcard include/config/lo/reserved0/mask.h) \
    $(wildcard include/config/lo/reserved0/shift.h) \
    $(wildcard include/config/lo/size/mask.h) \
    $(wildcard include/config/lo/size/shift.h) \
    $(wildcard include/config/lo/size/default.h) \
    $(wildcard include/config/hi/match/address/mask.h) \
    $(wildcard include/config/hi/match/address/shift.h) \
    $(wildcard include/config/hi/match/address/default.h) \
    $(wildcard include/config/lo/enable/mask.h) \
    $(wildcard include/config/lo/enable/shift.h) \
    $(wildcard include/config/lo/enable/default.h) \
    $(wildcard include/config/mask/mask.h) \
    $(wildcard include/config/mask/shift.h) \
    $(wildcard include/config/mask/default.h) \
    $(wildcard include/config/data/mask.h) \
    $(wildcard include/config/data/shift.h) \
    $(wildcard include/config/data/default.h) \
    $(wildcard include/config/retry/timeout/timer/value/mask.h) \
    $(wildcard include/config/retry/timeout/timer/value/shift.h) \
    $(wildcard include/config/retry/timeout/timer/value/default.h) \
    $(wildcard include/config/remap/offset/mask.h) \
    $(wildcard include/config/remap/offset/shift.h) \
    $(wildcard include/config/remap/offset/default.h) \
    $(wildcard include/config/remap/reserved0/mask.h) \
    $(wildcard include/config/remap/reserved0/shift.h) \
    $(wildcard include/config/remap/unused/3/1/mask.h) \
    $(wildcard include/config/remap/unused/3/1/shift.h) \
    $(wildcard include/config/remap/unused/3/1/default.h) \
    $(wildcard include/config/remap/access/en/mask.h) \
    $(wildcard include/config/remap/access/en/shift.h) \
    $(wildcard include/config/remap/access/en/default.h) \
  include/linux/brcmstb/7435b0/bchp_pcie_misc_hard.h \
  include/linux/brcmstb/7435b0/bchp_pcie_misc_perst.h \
  include/linux/brcmstb/7435b0/bchp_pcie_rc_cfg_pcie.h \
  include/linux/brcmstb/7435b0/bchp_pcie_rc_cfg_type1.h \
  include/linux/brcmstb/7435b0/bchp_pcie_rc_cfg_vendor.h \
  include/linux/brcmstb/7435b0/bchp_sata_top_ctrl.h \
  include/linux/brcmstb/7435b0/bchp_sdio_0_cfg.h \
  include/linux/brcmstb/7435b0/bchp_sun_top_ctrl.h \
    $(wildcard include/config/sw/init/0/monitor.h) \
    $(wildcard include/config/sw/init/1/monitor.h) \
    $(wildcard include/config/sw/init/0/monitor/reserved0/mask.h) \
    $(wildcard include/config/sw/init/0/monitor/reserved0/shift.h) \
    $(wildcard include/config/sw/init/0/monitor/sata/sw/init/mask.h) \
    $(wildcard include/config/sw/init/0/monitor/sata/sw/init/shift.h) \
    $(wildcard include/config/sw/init/0/monitor/moca/sw/init/mask.h) \
    $(wildcard include/config/sw/init/0/monitor/moca/sw/init/shift.h) \
    $(wildcard include/config/sw/init/0/monitor/genet1/sw/init/mask.h) \
    $(wildcard include/config/sw/init/0/monitor/genet1/sw/init/shift.h) \
    $(wildcard include/config/sw/init/0/monitor/genet0/sw/init/mask.h) \
    $(wildcard include/config/sw/init/0/monitor/genet0/sw/init/shift.h) \
    $(wildcard include/config/sw/init/0/monitor/usb1/sw/init/mask.h) \
    $(wildcard include/config/sw/init/0/monitor/usb1/sw/init/shift.h) \
    $(wildcard include/config/sw/init/0/monitor/usb0/sw/init/mask.h) \
    $(wildcard include/config/sw/init/0/monitor/usb0/sw/init/shift.h) \
    $(wildcard include/config/sw/init/0/monitor/not/used/sw/init/23/mask.h) \
    $(wildcard include/config/sw/init/0/monitor/not/used/sw/init/23/shift.h) \
    $(wildcard include/config/sw/init/0/monitor/ddr1/sw/init/mask.h) \
    $(wildcard include/config/sw/init/0/monitor/ddr1/sw/init/shift.h) \
    $(wildcard include/config/sw/init/0/monitor/ddr0/sw/init/mask.h) \
    $(wildcard include/config/sw/init/0/monitor/ddr0/sw/init/shift.h) \
    $(wildcard include/config/sw/init/0/monitor/memc1/sw/init/mask.h) \
    $(wildcard include/config/sw/init/0/monitor/memc1/sw/init/shift.h) \
    $(wildcard include/config/sw/init/0/monitor/memc0/sw/init/mask.h) \
    $(wildcard include/config/sw/init/0/monitor/memc0/sw/init/shift.h) \
    $(wildcard include/config/sw/init/0/monitor/xpt/sw/init/mask.h) \
    $(wildcard include/config/sw/init/0/monitor/xpt/sw/init/shift.h) \
    $(wildcard include/config/sw/init/0/monitor/raaga1/sw/init/mask.h) \
    $(wildcard include/config/sw/init/0/monitor/raaga1/sw/init/shift.h) \
    $(wildcard include/config/sw/init/0/monitor/raaga0/sw/init/mask.h) \
    $(wildcard include/config/sw/init/0/monitor/raaga0/sw/init/shift.h) \
    $(wildcard include/config/sw/init/0/monitor/aio/sw/init/mask.h) \
    $(wildcard include/config/sw/init/0/monitor/aio/sw/init/shift.h) \
    $(wildcard include/config/sw/init/0/monitor/gfx/sw/init/mask.h) \
    $(wildcard include/config/sw/init/0/monitor/gfx/sw/init/shift.h) \
    $(wildcard include/config/sw/init/0/monitor/avd0/sw/init/mask.h) \
    $(wildcard include/config/sw/init/0/monitor/avd0/sw/init/shift.h) \
    $(wildcard include/config/sw/init/0/monitor/svd0/sw/init/mask.h) \
    $(wildcard include/config/sw/init/0/monitor/svd0/sw/init/shift.h) \
    $(wildcard include/config/sw/init/0/monitor/dvp/hr/sw/init/mask.h) \
    $(wildcard include/config/sw/init/0/monitor/dvp/hr/sw/init/shift.h) \
    $(wildcard include/config/sw/init/0/monitor/dvp/ht/sw/init/mask.h) \
    $(wildcard include/config/sw/init/0/monitor/dvp/ht/sw/init/shift.h) \
    $(wildcard include/config/sw/init/0/monitor/vec/sw/init/mask.h) \
    $(wildcard include/config/sw/init/0/monitor/vec/sw/init/shift.h) \
    $(wildcard include/config/sw/init/0/monitor/bvn/sw/init/mask.h) \
    $(wildcard include/config/sw/init/0/monitor/bvn/sw/init/shift.h) \
    $(wildcard include/config/sw/init/0/monitor/not/used/sw/init/7/mask.h) \
    $(wildcard include/config/sw/init/0/monitor/not/used/sw/init/7/shift.h) \
    $(wildcard include/config/sw/init/0/monitor/ebi/sw/init/mask.h) \
    $(wildcard include/config/sw/init/0/monitor/ebi/sw/init/shift.h) \
    $(wildcard include/config/sw/init/0/monitor/pcie/sw/init/mask.h) \
    $(wildcard include/config/sw/init/0/monitor/pcie/sw/init/shift.h) \
    $(wildcard include/config/sw/init/0/monitor/webcpu/start/sw/init/mask.h) \
    $(wildcard include/config/sw/init/0/monitor/webcpu/start/sw/init/shift.h) \
    $(wildcard include/config/sw/init/0/monitor/webcpu/sw/init/mask.h) \
    $(wildcard include/config/sw/init/0/monitor/webcpu/sw/init/shift.h) \
    $(wildcard include/config/sw/init/0/monitor/ext/sys/sw/init/mask.h) \
    $(wildcard include/config/sw/init/0/monitor/ext/sys/sw/init/shift.h) \
    $(wildcard include/config/sw/init/0/monitor/cpu/sw/init/mask.h) \
    $(wildcard include/config/sw/init/0/monitor/cpu/sw/init/shift.h) \
    $(wildcard include/config/sw/init/0/monitor/sys/ctrl/sw/init/mask.h) \
    $(wildcard include/config/sw/init/0/monitor/sys/ctrl/sw/init/shift.h) \
    $(wildcard include/config/sw/init/1/monitor/reserved0/mask.h) \
    $(wildcard include/config/sw/init/1/monitor/reserved0/shift.h) \
    $(wildcard include/config/sw/init/1/monitor/spare1/sw/init/mask.h) \
    $(wildcard include/config/sw/init/1/monitor/spare1/sw/init/shift.h) \
    $(wildcard include/config/sw/init/1/monitor/m2mc1/sw/init/mask.h) \
    $(wildcard include/config/sw/init/1/monitor/m2mc1/sw/init/shift.h) \
    $(wildcard include/config/sw/init/1/monitor/sid/sw/init/mask.h) \
    $(wildcard include/config/sw/init/1/monitor/sid/sw/init/shift.h) \
    $(wildcard include/config/sw/init/1/monitor/v3d/top/sw/init/mask.h) \
    $(wildcard include/config/sw/init/1/monitor/v3d/top/sw/init/shift.h) \
    $(wildcard include/config/sw/init/1/monitor/vice21/sw/init/mask.h) \
    $(wildcard include/config/sw/init/1/monitor/vice21/sw/init/shift.h) \
    $(wildcard include/config/sw/init/1/monitor/vice20/sw/init/mask.h) \
    $(wildcard include/config/sw/init/1/monitor/vice20/sw/init/shift.h) \
    $(wildcard include/config/sw/init/1/monitor/uhfr/sw/init/mask.h) \
    $(wildcard include/config/sw/init/1/monitor/uhfr/sw/init/shift.h) \
    $(wildcard include/config/serial/adr/cfg/mask.h) \
    $(wildcard include/config/serial/adr/cfg/shift.h) \
    $(wildcard include/config/serial/adr/cfg/default.h) \
    $(wildcard include/config/probe/mux/sel/mask.h) \
    $(wildcard include/config/probe/mux/sel/shift.h) \
    $(wildcard include/config/probe/mux/sel/default.h) \
    $(wildcard include/config/dly/disable/mask.h) \
    $(wildcard include/config/dly/disable/shift.h) \
    $(wildcard include/config/dly/disable/default.h) \
    $(wildcard include/config/spi/mode/mask.h) \
    $(wildcard include/config/spi/mode/shift.h) \
    $(wildcard include/config/ssp/module/enable/mask.h) \
    $(wildcard include/config/ssp/module/enable/shift.h) \
    $(wildcard include/config/ssp/module/enable/default.h) \
  include/linux/brcmstb/7435b0/bchp_timer.h \
  include/linux/brcmstb/7435b0/bchp_uarta.h \
  include/linux/brcmstb/7435b0/bchp_uartb.h \
  include/linux/brcmstb/7435b0/bchp_uartc.h \
  include/linux/brcmstb/7435b0/bchp_usb1_ctrl.h \
  include/linux/brcmstb/7435b0/bchp_usb_ctrl.h \
  include/linux/brcmstb/7435b0/bchp_wktmr.h \
  include/linux/brcmstb/7435b0/brcmirq.h \

arch/mips/brcmstb/standby.o: $(deps_arch/mips/brcmstb/standby.o)

$(deps_arch/mips/brcmstb/standby.o):
